### ISSUE TITLE
Hover Mode post being struck by lightning

### ISSUE THREAD

**Issue by bttfhillvalley** [bttfhillvalley/vc-cleo-scripts#11]
Hover mode appears to be bugged after you are struck by lightning.  

Using a Pay 'n' Spray doesn't repair the flying circuits on the car.  
Additionally any subsequent time machines which are spawned (including the JVT) will not convert to hover mode.

Also tested destroying the time machine with the broken flying circuits before spawning a new one and get the same result, the newly spawned time machine will not enter hover mode.

**Comment by KyonkoYuuki** [comment]
Hover mode is now local to each time machine and not global.

**Comment by KyonkoYuuki** [comment]
Flying circuits repair needs to be revisited at some point to be tied to the future.
