### ISSUE TITLE
BTTF III DeLorean's hoodbox sparks alignment

### ISSUE THREAD

**Issue by bttfhillvalley** [bttfhillvalley/vc-cleo-scripts#13]
The spark effects on the BTTF III DeLorean's hood box are out of alignment.  
More noticeable on the offroad variant where the sparks are above the box.

The sparks move more drastically out of alignment when in hover mode when banking left/right, up/down.

**Comment by KyonkoYuuki** [comment]
Fixed, was missing speed adjustment function.
