### ISSUE TITLE
(LITE) Game will crash when in times between 1910-01-01 and <1980-01-01

### ISSUE THREAD

**Issue by Carlos85G** [bttfhillvalley/vc-cleo-scripts#17]
Using LITE version.

When travelling to DEC 31 1909 23:59 and waiting one minute, the game will crash.

When trying to travel to any time between (and including) JAN 01 1910 00:00 and DEC 31 1979 23:59, the game crashes before returning from black screen.

JAN 01 1980 00:00 works fine.

**Comment by Carlos85G** [comment]
Issue solves when compiled file CLEO\Map.cs is removed from the directory. The following compiled files should be removed from the repository:

CLEO\Map.cs
CLEO\1955\TwinPinesRipple.s
CLEO\1955\BarnProps.s

Thanks to Mike for pointing to the possible root if the issue.

**Comment by bttfhillvalley** [comment]
Issue caused by compiled scripts from Main being included in the repository. The compiled scripts have been removed and the issue is no longer present.
