### ISSUE TITLE
Instant crash when entering generic 2015 vehicles - Error Incorrect opcode ID: 2005

### ISSUE THREAD

**Issue by bttfhillvalley** [bttfhillvalley/vc-cleo-scripts#5]
Steps to recreate:
Start game and spawn the DeLorean, get in and travel to any date from Jan 01 2010 onwards.
Drive/fly around until you locate a generic 2015 vehicle, e.g. dmc-13, audi, griff's bmw, etc.
On entering a 2015 vehicle, you will get an instant crash with a cleo.asi popup stating "Incorrect opcode ID: 2005"

![cleo asi_error](https://user-images.githubusercontent.com/53920904/182572770-4e1e3d87-c26f-481b-aa6a-8bda9d9c725e.png)

**Comment by KyonkoYuuki** [comment]
Turns out there were a few issues.  the keybind changed with the move to CLEO and wasn't updated here, and then the opcode was also changed.  Fixed now.  This bug was actually in the main script and not CLEO
