### ISSUE TITLE
train impales it's self when falling with the engine off from great height 

### ISSUE THREAD

**Issue by HV-Leaf** [bttfhillvalley/vc-cleo-scripts#7]
![image](https://user-images.githubusercontent.com/99577377/221789584-fc6e86e8-8b49-4e19-94e0-bc406ec4149d.png)

**Comment by KyonkoYuuki** [comment]
yes, there is no limit to how far the tender can move at this time.

**Comment by KyonkoYuuki** [comment]
Limited movement of the tender to 10 degrees in pitch for now.
