### ISSUE TITLE
delorean spawns and instantly destroyed when using stock scm

### ISSUE THREAD

**Issue by HV-Leaf** [bttfhillvalley/vc-cleo-scripts#9]
![image](https://user-images.githubusercontent.com/99577377/221794957-c4ef1c26-9de2-4b13-879a-5e772d124037.png)

**Comment by KyonkoYuuki** [comment]
My guess is you haven't built the new scripts after the renaming.  If the Delorean didn't have its parts hidden, you're missing the script.
